# Generated by Django 4.1.4 on 2022-12-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_busket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Busket',
            new_name='Basket',
        ),
    ]
