# Generated by Django 4.1.4 on 2022-12-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0004_order_orderinbasket_order_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderInBasket',
            new_name='OrderProduct',
        ),
    ]
