# Generated by Django 4.1.4 on 2023-01-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('ebay', '0007_remove_order_address_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='session_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session', verbose_name='сессия'),
        ),
    ]
