# Generated by Django 4.1.4 on 2023-01-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0011_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='order', through='ebay.OrderProduct', to='ebay.product'),
        ),
    ]
