# Generated by Django 4.1.4 on 2023-02-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0012_alter_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
